// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";

const DB_PORT = env("POSTGRES_PORT")
const DB_USER = env("POSTGRES_USER")
const DB_PASSWORD = env("POSTGRES_PASSWORD")
const DB_NAME = env("POSTGRES_DB")

const getDatabaseUrl = () => {
  const url = env("DATABASE_URL");
  if (!url) {
    return `postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}`;
  }
  return url;
};

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: `bun run prisma/seed.ts`
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});